name: Continuous Integration

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run this workflow every day at 1:31 AM and 12:31 PM
  schedule:
    - cron: "31 1,12 * * *"

  # Run this workflow on push to main
  push:
    branches:
      - main

  # Run this workflow on pull request to main
  pull_request:
    branches:
      - main

jobs:
  linter:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Linter
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  typecheck:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Typecheck
    uses: ./.github/workflows/typecheck.yml

  shellcheck:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Shellcheck
    uses: ./.github/workflows/shellcheck.yml

  markdownlint:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Markdownlint
    uses: ./.github/workflows/markdownlint.yml

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: ./.github/workflows/todo.yml

  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Pull Request Validation
    uses: ./.github/workflows/pr-review.yml
