name: Pull Request Validation

concurrency:
  group: pull_request_${{ github.event.number }}
  cancel-in-progress: true

on:
  # Run this workflow on pull request to main
  pull_request:
    branches:
      - main

jobs:
  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Setup Danger Files
        run: |
          echo "Setting up Danger files..."
          mv tools/danger/* .

      - uses: actions/setup-node@v3
        with:
          node-version: "v18.15.0"

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Danger JS Action
        uses: danger/danger-js@11.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
